version: '3.4'

services:
  site-dev:
    build:
      context: client
      target: base-target
      args:
        npm_install_command: install
    volumes:
      - ./client:/usr/src/app
      - nodemodules:/usr/src/app/node_modules:delegated
      - next:/usr/src/app/.next
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run dev
  storybook:
    build:
      context: client
      target: base-target
      args:
        npm_install_command: install
    volumes:
      - ./client:/usr/src/app
      - nodemodules:/usr/src/app/node_modules:delegated
      - next:/usr/src/app/.next
    ports:
      - 6006:6006
    command: npm run storybook
  site-test:
    build:
      context: client
      target: base-target
      args:
        npm_install_command: install
    volumes:
      - ./client:/usr/src/app
      - nodemodules:/usr/src/app/node_modules:delegated
      - next:/usr/src/app/.next
    command: npm test
  ci:
    build:
      context: client
      target: ci-target
    volumes:
      - ./client:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
      - next:/usr/src/app/.next
  build-test:
    build:
      context: client
      target: build-target
    volumes:
      - ./client:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
      - next:/usr/src/app/.next
volumes:
  nodemodules: {}
  next: {}