
on: [pull_request, workflow_dispatch]
  
jobs:
  client:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./client/
    
    steps:
    - uses: actions/checkout@v3
    - name: Configure environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
