name: Client
on: 
  pull_request:
  push:
    branches:
      - 'master'
  
  workflow_dispatch:
  
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    
    steps:
    - uses: actions/checkout@v3
    - name: Build app
      run: npm run build
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    steps:
    - uses: actions/checkout@v3
    - name: Run approval tests
      run: npm test
