name: Client
on: [pull_request, workflow_dispatch]
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    
    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: docker compose build
    - name: Build app
      run: docker compose run build-test
#     - name: Run approval tests
#       run: docker compose run site-test
