
on: pull_request
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: cd client
    - run: npm install
    
  lint:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: cd client
    - run: npm lint
