
on: [pull_request, workflow_dispatch]
  
jobs:
  client:
    runs-on: ubuntu-18.04
    
    steps:
    - working-directory: client
    - uses: actions/checkout@v3
    - name: Build
      run: docker compose build
#     - name: Run approval tests
#       run: docker compose run site-test
