
on: [pull_request, workflow_dispatch]
  
jobs:
  client:
    runs-on: ubuntu-18.04
    
    steps:
    - working-directory: client
    - uses: actions/checkout@v3
    - name: Configure environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
