name: Client
on: 
  pull_request:
    types: ['opened', 'reopened', 'edited']
  push:
    branches:
      - 'master'
  
  workflow_dispatch:
  
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    
    steps:
    - uses: actions/checkout@v3
    - name: Build app
      run: docker compose build build-test
#     - name: Run approval tests
#       run: docker compose run site-test
